### ISSUE TITLE
Unsupported argument

### ISSUE THREAD

**Issue by hasretsariyer** [hashicorp/learn-terraform-multicloud-kubernetes#4]
I run `terraform init`. Then I run apply command. Terraform version is v1.1.7.
The result is here:

`terraform apply

╷
│ Error: Unsupported argument
│ 
│   on main.tf line 48, in module "eks":
│   48:   subnets         = module.vpc.private_subnets
│ 
│ An argument named "subnets" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 51, in module "eks":
│   51:   workers_group_defaults = {
│ 
│ An argument named "workers_group_defaults" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 55, in module "eks":
│   55:   worker_groups = [
│ 
│ An argument named "worker_groups" is not expected here.
╵`

How can I fix it?

**Comment by hiimivantang** [comment]
`workers_group_defaults`, `worker_groups` and `subnets` arguments have been renamed to `self_managed_node_group_defaults`, `self_managed_node_groups` and `subnet_ids` respectively in terraform-aws-eks provider v18.x. 

You can get this to work by specifying version <18.x. E.g.

```
diff --git a/eks/main.tf b/eks/main.tf
index aa72185..ef00e98 100644
--- a/eks/main.tf
+++ b/eks/main.tf
@@ -43,6 +43,7 @@ module "vpc" {
 
 module "eks" {
   source          = "terraform-aws-modules/eks/aws"
+  version = "17.24.0"
   cluster_name    = local.cluster_name
   cluster_version = "1.21"
   subnets         = module.vpc.private_subnets
```
